import static org.junit.Assert.assertNull;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import jdk.internal.jline.internal.TestAccessible;

class LCATest {

	@Test
	void findLowestCATest() {
		BT bt = new BT();
		bt.insert(7);
		bt.insert(5);
		bt.insert(3);
		bt.insert(1);
		bt.insert(4);
		bt.insert(6);
		bt.insert(9);
		bt.insert(8);
		bt.insert(12);
		bt.insert(11);
		bt.insert(13);

		/*			    7
		 * 			 /    \
		 *          5       9
		 *        /   \   /   \
		 *      3      6 8     12
		 *    /   \           /   \
		 *  1      4        11     13
		 *  This is the tree generated by the above code
		 */

		LCA lca = new LCA(3, 6, bt);
		assertEquals(5, lca.findLowestCommonAncestor());

		lca = new LCA(1, 4, bt);
		assertEquals(3, lca.findLowestCommonAncestor());

		lca = new LCA(5, 9, bt);
		assertEquals(7, lca.findLowestCommonAncestor());
	}

	// Ensure that when a Binary Tree is created but with
	// no values added, it is null
	@Test
	void nullBinaryTree() {
		BT nullBT = new BT();
		assertNull(nullBT.root);
	}

	@Test
	void testBTInsert() {
		BT bt = new BT();
		bt.insert(7);
		assertEquals(7, bt.root.val);

		bt.insert(5);
		bt.insert(9);
		assertEquals(5, bt.root.left.val);
		assertEquals(9, bt.root.right.val);

		bt.insert(3);
		bt.insert(6);
		bt.insert(8);
		bt.insert(12);
		assertEquals(3, bt.root.left.left.val);
		assertEquals(6, bt.root.left.right.val);
		assertEquals(8, bt.root.right.left.val);
		assertEquals(12, bt.right.right.val);
	}

	@Test 
	void testReturnLCA() {
		BT bt = new BT();
		bt.insert(7);
		bt.insert(5);
		bt.insert(3);
		bt.insert(1);
		bt.insert(4);
		bt.insert(6);
		bt.insert(9);
		bt.insert(8);
		bt.insert(12);
		bt.insert(11);
		bt.insert(13);
		
		/*			    7
		 * 			 /    \
		 *          5       9
		 *        /   \   /   \
		 *      3      6 8     12
		 *    /   \           /   \
		 *  1      4        11     13
		 *  This is the tree generated by the above code
		 */

		 LCA lca = new LCA(5, 9, bt);
		 assertEquals(lca.findLowestCommonAncestor(), lca.returnLCA());
	}

}
